# Generated by Django 5.2.9 on 2025-12-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.appointment')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=50)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_used', models.CharField(max_length=100)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.drug')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.treatment')),
            ],
        ),
    ]
