# Generated by Django 5.2.9 on 2025-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_dentist_user_remove_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='dental_issues',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='diseases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
